# Generated by Django 3.2 on 2022-03-05 21:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('city', models.TextField(choices=[('copenhagen', 'Copenhagen'), ('florence', 'Florence')])),
                ('category', models.TextField(choices=[('museum', 'Museum'), ('monument', 'Monument'), ('park', 'Park'), ('day_trip', 'Day Trip'), ('sports', 'Sports'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('culture', 'Cultural'), ('playground', 'Playground'), ('activity', 'Activity')])),
                ('description', models.TextField()),
                ('excerpt', models.TextField()),
                ('price', models.IntegerField(choices=[(0, 'Free'), (1, 'Costs Money')], default=1)),
                ('directions', models.URLField(blank=True, max_length=400)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('likes', models.ManyToManyField(blank=True, related_name='experience_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=5)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.experience')),
                ('likes', models.ManyToManyField(blank=True, related_name='review_like', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
